# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-30 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webgroup',
            options={'verbose_name': '聊天组', 'verbose_name_plural': '聊天组'},
        ),
    ]
